= Desarrollo de una aplicación desde cero: El patrón MVC y la capa de presentación.
La metaweb
:hp-tags: JSF, Java Server Faces, MVC, Facelets, Maven
:published_at: 2015-06-30

Hola de nuevo. En este post completaremos el desarrollo inicial de nuestra aplicación con la implementación de la capa de presentación. Pero antes de empezar a añadir elementos, considero importante mostraros el concepto del patrón Modelo-Vista-Controlador ya que su comprensión nos va a ayudar a entender la función de cada elemento dentro de esta capa.

== El patrón MVC

Consiste en una solución probada al problema que plantea la separación de la presentación o vista y el modelo en la arquitectura de una aplicación. Esta separación se logra introduciendo un tercer componente, el controlador.

Aunque la anterior definición está clara, no lo está tanto como este patrón encaja en una aplicación web Java empresarial basada en la tecnología Java EE como la que en este post vamos a concluir. Y tampoco como cada parte M, V y C se sitúa dentro de la arquitectura de capas de nuestra aplicación.

Las tres partes del patrón MVC se sitúan en Java EE dentro de la capa de presentación.

Veamos una definición para cada parte M, V, y C y la correspondencia con cada uno de los elementos de la aplicación:

* Modelo: Es una representación del *modelo* (lo escribo en negrita para distingirlo con claridad) de la aplicación entendido este último como todo el conjunto de datos y toda la lógica de negocio que procesa esos datos. En JSF el Modelo se implementa en las clases backed bean. El *modelo* tiene una parte de datos y otra de comportamiento. Veamos cada una por separado:

** Parte de datos del *modelo*: Son los beans de entidad JPA de la capa de persistencia. En el Modelo se representan como atributos de los backed beans con el mismo tipo que los entity beans JPA.

** Parte de comportamiento del *modelo*: Son los beans de sesión EJB de la capa de negocio/DAO/servicio. En el Modelo se representan dentro de los métodos de evento de los backed beans, como llamadas a los métodos de estos beans de sesión.

En resumen, el Modelo se implementa en los backed beans y en JSF es una representación o punto de acceso al *modelo* de la aplicación.

* Vista: 











correspondencia MVC y capas