= ¡399 euros! ¡Tonto el último! Y porqué decidí ser "el último".
La metaweb
:hp-tags: Offtopic, Reciclaje, Ahorro, Consumismo, Portátil, Laptop
:published_at: 2015-11-03

Esta mañana, cuando salía de mi domicilio, he procedido a retirar la propaganda que suele sobresalir del buzón. Entre ellas destacaba por su habitual tamaño "extra size" la de una conocida cadena de venta de productos de electrónica y electrodomésticos. Me gusta hojear sus páginas porque aparte de las omnipresentes televisiones (o televisores) puedes ver algunos productos interesantes que acaban de aterrizar en el mercado.

En portada a todo color veo un portátil de gama media con el atractivo precio de 399 euros. Probablemente se trate de una buena oferta y si estamos pensando en adquirir un portátil para uso general sea una buena opción. Pero ¡alto!, qué hay de nuestro viejo portátil, aún arranca y hasta hoy nos ha dado un gran servicio. Bueno... la pantalla está descolgada y algunas aplicaciones se llevan media vida queriendo arrancar hasta que finalmente lo consiguen, por no hablar de la betería que dura poco más de un cuarto de hora. Ante este panorama lo cierto es que la opción de la compra toma bastante fuerza.

En este primer Offtopic, no demasiado off porque nos quedamos en el terreno de la Informática, os propongo la opción de la no compra. Os daré una lista de acciones para revitalizar nuestro portátil y permitirle así que siga dándonos un buen servicio algunos añitos más. Todos los puntos de la lista están comprobados ya que yo mismo tomé la decisión de demorar la compra y hasta ahora todo han sido satisfacciones. 

Aclararos antes de empezar que tampoco se puede hacer milagros. Si nuestro portátil es un gama baja del año 

Empezamos.

===La fuerza de la costumbre: Mi teclado.

Uno de los grandes puntos a favor de seguir con tu antiguo portátil es el grado de adaptación que se tiene en su uso. Esto se nota especialmente en el teclado. Nada como el teclado de tu portátil cuando estás tirando líneas de código y usando los atajos del teclado. Seguramente lo habrás notado cuando intentas seguir el mismo ritmo en el ordanador de un amigo o familiar, la tasa de errores es mucho mayor, aparte de que la sensación que te ofrece no es la misma.

Esto mismo aunque de forma no tan evidente ocurre con la pantalla, el formato, tamaño, temperatura de color y brillo no es al que estamos acostumbrados.

===Las largas esperas observando el parpadeo del led del disco duro.

Este es uno de los puntos que pesan más a la hora de cambiar de portátil. Un modelo del año 2008, que es el que 